#!/usr/bin/env node

'use strict';

//global utils
var chalk = require( 'chalk' ) //TODO: make much color
var v8flags = require( 'v8flags' )
var minimist = require( 'minimist' )
var mreverse = require( 'minimist-reverse' )
require( 'shelljs/global' )

//directories
var plugins = process.cwd() + "/plugins/"

if ( process.argv.length < 3 ) {
    console.log( 'Please enter a command' );

    process.exit( 1 )
}

//complete command
var command = argv[ '_' ][ 0 ]

//arguments
var argv = minimist( process.argv.slice( 2 ) )

//full command
var fullcommand = mreverse( argv )

if ( command == 'list' ) {

    echo( ls( plugins ).sed( ' ', '\n' ) )
    process.exit( 1 )

}

//does command file exist?
var existsFile = require( 'exists-file' )
if ( existsFile.sync( plugins + command ) == true ) {

    runcommand()

} else {

    echo( 'No such command' )

}

function runcommand() {
    exec( plugins + fullcommand, function ( code, stdout, stderr ) {

        if ( code == 0 && stdout == false ) {

            console.log( "Your program didn't output anything." )

        }

    } );
}
