#!/usr/bin/env node

'use strict';

var chalk = require('chalk') //TODO: make much color
var v8flags = require('v8flags')
var minimist = require('minimist')
var mreverse = require('minimist-reverse')
var shell = require("shelljs")

var plugins = "./plugins/"

process.env.INIT_CWD = process.cwd()

if (process.argv.length < 1) {
  process.exit(1)
}

var argv = minimist(process.argv.slice(2))
var tasks = mreverse(argv)

console.log("Executing: " + tasks)

//shell.exec(plugins + tasks);
