#!/usr/bin/env node

'use strict';

var v8flags = require('v8flags');
var argv = require('minimist')(process.argv.slice(2));
var shell = require("shelljs");

var plugins = "./plugins/";

var tasksFlag = argv.T || argv.tasks;
var tasks = argv._;
var toRun = tasks.length ? tasks : ['default'];

process.env.INIT_CWD = process.cwd();

if (process.argv.length < 3) {
  process.exit(1);
}

console.log("Executing: " + tasks);

shell.exec(plugins + tasks);
